hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "mods/accessories.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/blaha-replushed.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/chunkyborder.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
metafile = true

[[files]]
file = "mods/continents.pw.toml"
metafile = true

[[files]]
file = "mods/daisy.pw.toml"
metafile = true

[[files]]
file = "mods/defaulted-hotkeys.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/flashfreeze.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/hexcasting.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/observable.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/sable.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/unloaded-activity.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
metafile = true
